[package]
name = "rtiler-v2"
version = "0.1.0"
authors = ["Robert Usher <266585+dcchut@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rayon = "1.0"
pbr = "1.0.1"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
simplesvg = "0.4.0"
rand = "0.6.5"
time = "0.1"
clap = "2.32.0"